//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartridgeManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartriges
    {
        public int idCartrige { get; set; }
        public string type { get; set; }
        public string model { get; set; }
        public Nullable<int> serialnumb { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> gurantee { get; set; }
        public Nullable<int> idState { get; set; }
        public Nullable<int> idRepair { get; set; }
        public string comment { get; set; }
    
        public virtual Repairs Repairs { get; set; }
        public virtual States States { get; set; }
    }
}
